### ISSUE TITLE
Feature Request: Make 'bit' an attribute

### ISSUE THREAD

**Issue by jburns24** [dhoer/chef-iedriver#4]
Currently the variable bit is calculated using the 'node['kernal']['machine']. This is an issue for IE as 64 bit version of IE will open 32-bit tabs. You can change this by enabling "Enhanced Protection Mode" But IEDriver requires this attribute to be disabled. The result is this cookbook downloads a 64-bit driver and runs it on a 32-bit ie process. This works in most cases but when trying to do something like `driver.manage().cookies.deleteAllCookies()` the test will silently fail on this call due to the driver and browsers 'bit-ness' being different. Being that `node['kernal']['machine']` is set by Ohai and an automatic attribute there is no way for me to override it.

What do you think about making bit a configurable attribute that is set by default to `node['kernel']['machine'] == 'x86_64' ? 'x64' : 'Win32'`

**Comment by dhoer** [comment]
Add default['iedriver']['forcex86'] attribute that defaults to false to force a (32bit) installation on 64 bit systems.

**Comment by jburns24** [comment]
https://github.com/dhoer/chef-iedriver/pull/5
